// End-to-end licensing checks. Isolated data and simulated devices only.
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const { spawnSync } = require("node:child_process");
const { startTestServer, issueTestLicense } = require("./test-server.cjs");
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const output = path.resolve(__dirname, "../artifacts/licensing");
fs.mkdirSync(output, { recursive: true });
let server, browser;
(async () => {
  server = await startTestServer("licensing", () => {}, { activate: false });
  browser = await chromium.launch({ headless: true, executablePath: process.env.EDGE_EXE || "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const pageErrors = [];
  page.on("pageerror", (e) => pageErrors.push(e.message));
  await page.goto(server.base);
  await page.locator("#machine-code").waitFor({ state: "visible" });
  const machine = await page.locator("#machine-code").inputValue();
  assert.match(machine, /^LP1-[0-9A-F]{32}$/);
  assert.equal(await page.locator("#print-form").count(), 0);
  const session = await (await context.request.get(server.base + "/api/session")).json();
  const headers = { "x-csrf-token": session.csrf };
  for (const route of ["/api/devices", "/api/files", "/api/jobs", "/api/network", "/api/profiles", "/api/files/no-id/download", "/api/files/no-id/preview", "/app.js"]) {
    const result = await context.request.get(server.base + route);
    assert.equal(result.status(), 403, route);
    assert.equal((await result.json()).code, "license_required");
  }
  for (const route of ["/api/print", "/api/scan", "/api/files", "/api/network/repair", "/api/profiles"]) {
    const result = await context.request.post(server.base + route, { headers, data: {} });
    assert.equal(result.status(), 403, route);
    assert.equal((await result.json()).code, "license_required");
  }
  assert.equal((await context.request.post(server.base + "/api/license", { data: { code: "invalid" } })).status(), 403);
  const code = issueTestLicense(machine, "注册码验收办公室");
  const changedMachine = machine.slice(0, -1) + (machine.endsWith("0") ? "1" : "0");
  const wrongMachine = issueTestLicense(changedMachine);
  const parts = code.split(".");
  const claims = JSON.parse(Buffer.from(parts[1], "base64url"));
  claims.customer = "被篡改的单位";
  parts[1] = Buffer.from(JSON.stringify(claims)).toString("base64url");
  for (const invalid of ["invalid", wrongMachine, parts.join("."), "x".repeat(4097)]) {
    const result = await context.request.post(server.base + "/api/license", { headers, data: { code: invalid } });
    assert.equal(result.status(), 400);
    assert.equal(fs.existsSync(path.join(server.data, "license.json")), false);
  }
  const address = Object.values(os.networkInterfaces()).flat().find((a) => a.family === "IPv4" && !a.internal && /^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(a.address));
  assert.ok(address, "A LAN interface is required for the remote activation check");
  const remote = new URL(server.base);
  remote.hostname = address.address;
  const remoteContext = await browser.newContext();
  const remoteSession = await (await remoteContext.request.get(remote.href + "api/session")).json();
  const remoteStatus = await (await remoteContext.request.get(remote.href + "api/license")).json();
  assert.equal(remoteStatus.machineCode, null);
  assert.equal(remoteStatus.customer, null);
  assert.equal(remoteStatus.localAdmin, false);
  assert.equal((await remoteContext.request.post(remote.href + "api/license", { headers: { "x-csrf-token": remoteSession.csrf }, data: { code } })).status(), 403);
  const remotePage = await remoteContext.newPage();
  await remotePage.goto(remote.href);
  await remotePage.locator("#activation-remote").waitFor({ state: "visible" });
  assert.equal(await remotePage.locator("#activation-form").isVisible(), false);
  await page.locator("#registration-code").fill(wrongMachine);
  await page.locator("#activate-submit").click();
  await page.waitForFunction(() => document.getElementById("activation-error").textContent.includes("不匹配"));
  await page.screenshot({ path: path.join(output, "registration-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(output, "registration-mobile.png"), fullPage: true });
  const req = path.join(server.data, "unregistered-worker.json");
  const res = path.join(server.data, "unregistered-response.json");
  fs.writeFileSync(req, JSON.stringify({ license: "", operation: "devices", path: "", output: "", page: 0, print: null, scan: null, show_virtual: false, demo: false }));
  const worker = spawnSync(process.env.LANPRINT_EXE || path.resolve(__dirname, "../target/debug/lan-print.exe"), ["--worker", req, res], { windowsHide: true });
  assert.equal(worker.status, 1);
  assert.ok(JSON.parse(fs.readFileSync(res, "utf8")).error);
  await page.locator("#registration-code").fill(code);
  await page.locator("#activate-submit").click();
  await page.locator("#print-form").waitFor({ state: "visible" });
  await page.waitForFunction(() => document.getElementById("connection").textContent.includes("演示模式"));
  assert.equal((await context.request.get(server.base + "/api/devices")).status(), 200);
  assert.equal((await remoteContext.request.get(remote.href + "api/devices")).status(), 200);
  const saved = fs.readFileSync(path.join(server.data, "license.json"), "utf8");
  const newSession = await (await context.request.get(server.base + "/api/session")).json();
  assert.equal((await context.request.post(server.base + "/api/license", { headers: { "x-csrf-token": newSession.csrf }, data: { code: "bad" } })).status(), 400);
  assert.equal(fs.readFileSync(path.join(server.data, "license.json"), "utf8"), saved);
  await page.goto(server.base + "/register");
  await page.locator("#activation-success").waitFor({ state: "visible" });
  assert.match(await page.locator("#licensed-customer").textContent(), /注册码验收办公室/);
  await page.screenshot({ path: path.join(output, "registration-success.png"), fullPage: true });
  await server.stop();
  server = await startTestServer("licensing-restart", (directory) => fs.writeFileSync(path.join(directory, "license.json"), saved), { activate: false });
  const restarted = await (await fetch(server.base + "/api/license")).json();
  assert.equal(restarted.registered, true);
  assert.equal(restarted.machineCode, machine);
  assert.equal((await fetch(server.base + "/api/devices")).status, 200);
  fs.writeFileSync(path.join(server.data, "license.json"), '{"registered":true}');
  assert.equal((await fetch(server.base + "/api/devices")).status, 403);
  await page.goto(server.base);
  await page.locator("#activation-local").waitFor({ state: "visible" });
  await page.locator("#registration-code").fill(code);
  await page.locator("#activate-submit").click();
  await page.locator("#print-form").waitFor({ state: "visible" });
  fs.unlinkSync(path.join(server.data, "license.json"));
  assert.equal((await fetch(server.base + "/api/files")).status, 403);
  await server.stop();
  server = await startTestServer("licensing-normal", () => {}, { demo: false, activate: false });
  assert.equal((await fetch(server.base + "/api/devices")).status, 403);
  assert.match(await (await fetch(server.base)).text(), /activation-form/);
  assert.deepEqual(pageErrors, []);
  fs.writeFileSync(path.join(output, "report.json"), JSON.stringify({ passed: true, checks: ["unregistered API gate including demo", "CSRF", "invalid / wrong-machine / tampered / oversized codes", "LAN activation denied", "desktop and mobile UI", "worker command gate", "successful activation and existing license preservation", "LAN access after activation", "restart persistence", "damaged/deleted license relocks and recovery"] }, null, 2));
  console.log("PASS: licensing, issuer, API, LAN restrictions, worker gate, browser, persistence and recovery");
})().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); if (server) await server.stop(); });
